name: dempsey_nzgw2018
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.12
  - notebook
  - widgetsnbextension
  - numpy
  - scipy
  - ipykernel
  - ipython
  - ipywidgets
  - matplotlib